name: sqlflite_ppb_6
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.2
   # format DateTime
  intl: ^0.19.0
   # display todos in grid
  flutter_staggered_grid_view: ^0.7.0
  path: ^1.8.3
  image_picker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
